pipeline:
  run-api-starter-tests:
    image: node:10.11.0
    commands:
      - chmod +x ./bin/run.sh
      - ./bin/run.sh
    when:
      status: [ failure, success ]
      event: [ pull_request ]

services:
  mongo:
    image: mongo:4.0.3
branches: [ master, "*:master" ]
