version: '3.6'  
services:  
  mongo:
    command: mongod
    image: mongo:4.0.3
    networks:
      - ship
    ports:
      - "27017:27017" # map port to none standard port, to avoid conflicts with locally installed mongodb. 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  api:
    build:
      context: "./"
      dockerfile: Dockerfile.dev
    networks:
      - ship
    volumes:
      - "./src:/app/src"
    ports:
      - "3001:3001"

networks:
  ship:
    name: ship_network
